export const COUNTRIES = [
  { flag: '🇧🇷', name: 'Brasil', ddi: '+55', code: 'BR', minDigits: 10, maxDigits: 11 },
  { flag: '🇺🇸', name: 'Estados Unidos', ddi: '+1', code: 'US', minDigits: 10, maxDigits: 10 },
  { flag: '🇨🇦', name: 'Canadá', ddi: '+1', code: 'CA', minDigits: 10, maxDigits: 10 },
  { flag: '🇲🇽', name: 'México', ddi: '+52', code: 'MX', minDigits: 10, maxDigits: 10 },
  { flag: '🇦🇷', name: 'Argentina', ddi: '+54', code: 'AR', minDigits: 9, maxDigits: 10 },
  { flag: '🇨🇴', name: 'Colômbia', ddi: '+57', code: 'CO', minDigits: 10, maxDigits: 10 },
  { flag: '🇵🇪', name: 'Peru', ddi: '+51', code: 'PE', minDigits: 9, maxDigits: 9 },
  { flag: '🇨🇭', name: 'Chile', ddi: '+56', code: 'CL', minDigits: 9, maxDigits: 9 },
  { flag: '🇬🇧', name: 'Reino Unido', ddi: '+44', code: 'UK', minDigits: 10, maxDigits: 11 },
  { flag: '🇪🇸', name: 'Espanha', ddi: '+34', code: 'ES', minDigits: 9, maxDigits: 9 },
  { flag: '🇫🇷', name: 'França', ddi: '+33', code: 'FR', minDigits: 9, maxDigits: 9 },
  { flag: '🇩🇪', name: 'Alemanha', ddi: '+49', code: 'DE', minDigits: 10, maxDigits: 11 },
  { flag: '🇮🇹', name: 'Itália', ddi: '+39', code: 'IT', minDigits: 10, maxDigits: 10 },
  { flag: '🇵🇹', name: 'Portugal', ddi: '+351', code: 'PT', minDigits: 9, maxDigits: 9 },
  { flag: '🇦🇺', name: 'Austrália', ddi: '+61', code: 'AU', minDigits: 9, maxDigits: 9 },
  { flag: '🇯🇵', name: 'Japão', ddi: '+81', code: 'JP', minDigits: 10, maxDigits: 11 },
  { flag: '🇳🇿', name: 'Nova Zelândia', ddi: '+64', code: 'NZ', minDigits: 9, maxDigits: 9 },
  { flag: '🇿🇦', name: 'África do Sul', ddi: '+27', code: 'ZA', minDigits: 9, maxDigits: 10 },
  { flag: '🇮🇳', name: 'Índia', ddi: '+91', code: 'IN', minDigits: 10, maxDigits: 10 },
  { flag: '🇨🇳', name: 'China', ddi: '+86', code: 'CN', minDigits: 10, maxDigits: 11 },
];
